-- MySQL Script generated by MySQL Workbench
-- Sun Jun 26 22:36:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema car_rent_spring
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_rent_spring
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_rent_spring` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `car_rent_spring` ;

-- -----------------------------------------------------
-- Table `car_rent_spring`.`car_brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`car_brands` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`car_brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(90) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 40
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`car_models`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`car_models` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`car_models` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `car_model` VARCHAR(250) NOT NULL,
  `car_brands_id` INT NOT NULL,
  `car_classes_id` INT NOT NULL,
  PRIMARY KEY (`id`, `car_brands_id`, `car_classes_id`),
  INDEX `fk_car_models_car_brands1` (`car_brands_id` ASC) VISIBLE,
  CONSTRAINT `fk_car_models_car_brands1`
    FOREIGN KEY (`car_brands_id`)
    REFERENCES `car_rent_spring`.`car_brands` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`complete_sets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`complete_sets` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`complete_sets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `model_id` INT NOT NULL,
  `body_style_id` INT NOT NULL,
  `transmission_id` INT NULL DEFAULT NULL,
  `fuel_type_id` INT NOT NULL,
  `engine` DECIMAL(4,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `complete_sets_car_models_id_fk` (`model_id` ASC) VISIBLE,
  CONSTRAINT `complete_sets_car_models_id_fk`
    FOREIGN KEY (`model_id`)
    REFERENCES `car_rent_spring`.`car_models` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`tariffs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`tariffs` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`tariffs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rent_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `driver_price` DECIMAL(10,0) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`cars`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`cars` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`cars` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `graduation_year` YEAR NOT NULL,
  `model_id` INT NOT NULL,
  `brand_id` INT NOT NULL,
  `vin_code` VARCHAR(45) NOT NULL,
  `state_number` VARCHAR(45) NOT NULL,
  `available` TINYINT(1) NULL DEFAULT '1',
  `tariff_id` INT NOT NULL,
  `complete_set_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cars_car_models1_idx` (`model_id` ASC, `brand_id` ASC) VISIBLE,
  INDEX `fk_cars_tarifs1_idx` (`tariff_id` ASC) VISIBLE,
  INDEX `cars_complete_sets_id_fk` (`complete_set_id` ASC) VISIBLE,
  INDEX `FK8u2qxfl5fxb90neutelhsmt1w` (`brand_id` ASC) VISIBLE,
  CONSTRAINT `cars_complete_sets_id_fk`
    FOREIGN KEY (`complete_set_id`)
    REFERENCES `car_rent_spring`.`complete_sets` (`id`),
  CONSTRAINT `FK8u2qxfl5fxb90neutelhsmt1w`
    FOREIGN KEY (`brand_id`)
    REFERENCES `car_rent_spring`.`car_brands` (`id`),
  CONSTRAINT `fk_cars_car_models1`
    FOREIGN KEY (`model_id` , `brand_id`)
    REFERENCES `car_rent_spring`.`car_models` (`id` , `car_brands_id`),
  CONSTRAINT `fk_cars_tarifs1`
    FOREIGN KEY (`tariff_id`)
    REFERENCES `car_rent_spring`.`tariffs` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`users` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(166) NOT NULL,
  `first_name` VARCHAR(45) NULL DEFAULT NULL,
  `second_name` VARCHAR(45) NULL DEFAULT NULL,
  `document_info` VARCHAR(200) NOT NULL,
  `role` VARCHAR(50) NOT NULL,
  `blocked` BINARY(1) NULL DEFAULT '0',
  `phone` VARCHAR(20) NOT NULL,
  `salt` BLOB NULL DEFAULT NULL,
  `receive_notifications` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`orders` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT UNSIGNED NOT NULL,
  `car_id` INT NOT NULL,
  `manager_id` INT UNSIGNED NULL DEFAULT NULL,
  `docements` VARCHAR(256) NOT NULL,
  `day_counts` INT NULL DEFAULT NULL,
  `price` DECIMAL(10,2) UNSIGNED NOT NULL,
  `status` INT NULL DEFAULT '1',
  `with_driver` TINYINT(1) NULL DEFAULT '0',
  `manager_comment` VARCHAR(255) NULL DEFAULT NULL,
  `driver_price` DECIMAL(10,2) NULL DEFAULT '0.00',
  `rent_sum` DECIMAL(10,2) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_orders_users1_idx` (`client_id` ASC) VISIBLE,
  INDEX `FKd2p23ixwrrt395glgi9nnbj23` (`car_id` ASC) VISIBLE,
  INDEX `FK9qn4jar6kvccow7iyuo2mfuef` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `FK9qn4jar6kvccow7iyuo2mfuef`
    FOREIGN KEY (`manager_id`)
    REFERENCES `car_rent_spring`.`users` (`id`),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `car_rent_spring`.`users` (`id`),
  CONSTRAINT `FKd2p23ixwrrt395glgi9nnbj23`
    FOREIGN KEY (`car_id`)
    REFERENCES `car_rent_spring`.`cars` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`invoices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`invoices` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`invoices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_id` INT UNSIGNED NOT NULL,
  `type` INT UNSIGNED NOT NULL,
  `order_id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  `paid` TINYINT(1) NOT NULL DEFAULT '0',
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `invoices_id_uindex` (`id` ASC) VISIBLE,
  INDEX `fk_invoices_users1_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_invoices_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `car_rent_spring`.`orders` (`id`),
  CONSTRAINT `fk_invoices_users1`
    FOREIGN KEY (`client_id`)
    REFERENCES `car_rent_spring`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `car_rent_spring`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `car_rent_spring`.`transactions` ;

CREATE TABLE IF NOT EXISTS `car_rent_spring`.`transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `sum` DECIMAL(10,2) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `transactions_users_id_fk` (`user_id` ASC) VISIBLE,
  CONSTRAINT `transactions_users_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `car_rent_spring`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 41
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
